### ISSUE TITLE
DoRA Support

### ISSUE THREAD

**Issue by JunJi-JiaYue** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#105]
When I tried to get the model info of a DoRA model by Civitai URL (e.g. https://civitai.com/models/319865?modelVersionId=467045), I received the message `This model type is not supported: DoRA` and could not get it.
If I download the model manually and use the "Scan Models for Civitai" feature, files such as .civitai.info are created successfully.
I am using the WebUI forge version f0.0.17v1.8.0rc-latest-276-g29be1da7.

```
CHv1.8.6: Start open_model_url
CHv1.8.6: Start parse js msg
CHv1.8.6: End parse js msg
CHv1.8.6: Load model info of Charactor\pony\ibukiBlueArchive_v20ForPony.safetensors 484ea7cd03cb4da5883a48cda69d6a257e74f59591609a1f9204fad816a72507 in lora
CHv1.8.6: Send Url to js
CHv1.8.6: Start build_msg
CHv1.8.6: End build_msg
CHv1.8.6: End open_model_url
CHv1.8.6: Run get_model_id_from_url
CHv1.8.6: Getting model info for: 319865
CHv1.8.6: Request model info from civitai: 319865
CHv1.8.6: This model type is not supported: DoRA
Traceback (most recent call last):
  File "C:\Users\username\Documents\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\username\Documents\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\username\Documents\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\username\Documents\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (get_model_info_by_url) didn't receive enough output values (needed: 6, received: 1).
Wanted outputs:
    [state, textbox, textbox, dropdown, dropdown, <gradio.layouts.Column object at 0x000001D179E914B0>]
Received outputs:
    [None]
```

**Comment by zixaphir** [comment]
DoRA support added.
