### ISSUE TITLE
No results, nothing happening. TypeError NoneType

### ISSUE THREAD

**Issue by Fretag** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#129]
I use Forge, Is this something the Forge team needs to address? Seems like it came after the big update.  

Traceback (most recent call last):
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "F:\SD Forge Manual\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\SD Forge Manual\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\SD Forge Manual\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\SD Forge Manual\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "F:\SD Forge Manual\extensions\Stable-Diffusion-Webui-Civitai-Helper\browser\browser.py", line 67, in perform_search
    params = make_params(search)
  File "F:\SD Forge Manual\extensions\Stable-Diffusion-Webui-Civitai-Helper\browser\browser.py", line 275, in make_params
    frags = array_frags(key, val, frags)
  File "F:\SD Forge Manual\extensions\Stable-Diffusion-Webui-Civitai-Helper\browser\browser.py", line 259, in array_frags
    if len(vals) == 0:
TypeError: object of type 'NoneType' has no len()

**Comment by Fretag** [comment]
Am I the only person with this problem?

**Comment by Adzido** [comment]
I have the same problem, thats still not working.
