### ISSUE TITLE
No module named 'backend'

### ISSUE THREAD

**Issue by trojan-uma** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#145]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue
extensions show error when sd starting

## Screenshot for UI issue
No

## Console log's msg or screenshot for function issue
```
Launching Web UI with arguments: --medvram-sdxl --theme dark --port 65500 --xformers --xformers-flash-attention --opt-channelslast --skip-python-version-check
CHv1.8.12: Get Custom Model Folder
*** Error loading script: image_metadata.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\image_metadata.py", line 10, in <module>
        from backend.args import dynamic_args
    ModuleNotFoundError: No module named 'backend'

---
```

**Comment by aoleg** [comment]
+1 Same error.

**Comment by Zergland** [comment]
+1

**Comment by zixaphir** [comment]
Apologies for this. Should be fixed now.
