### ISSUE TITLE
I get this error message at startup

### ISSUE THREAD

**Issue by ttyksi** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#18]
*** Error loading script: civitai_helper.py
    Traceback (most recent call last):
      File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 31, in <module>
        "add_trigger_words_button": util.newer_version(util.webui_version(), '1.5.0', allow_equal=True),
      File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\util.py", line 253, in newer_version
        return parse_version(ver1) >= parse_version(ver2)
      File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\packaging\version.py", line 52, in parse
        return Version(version)
      File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\packaging\version.py", line 196, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object

---

I am a layman so I don't know the details, but it may be an inherent problem with using StabilityMatrix.

**Comment by popsoda27** [comment]
Hey, just wanted to come in to post an issue on this then I saw your post here, which is exactly the same error as what I received for this extension.

Here is my console log:
*** Error loading script: civitai_helper.py
    Traceback (most recent call last):
      File "E:\Downloads\stable-diffusion-webui-directml\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Downloads\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Downloads\stable-diffusion-webui-directml\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 31, in <module>
        "add_trigger_words_button": util.newer_version(util.webui_version(), '1.5.0', allow_equal=True),
      File "E:\Downloads\stable-diffusion-webui-directml\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\util.py", line 253, in newer_version
        return parse_version(ver1) >= parse_version(ver2)
      File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\packaging\version.py", line 54, in parse
        return Version(version)
      File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\packaging\version.py", line 198, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object

I'm on lshqqytiger's fork of A1111. This just happened to me today when I realized the Civitai helper UI tab went missing.

**Comment by obs945** [comment]
I had the same issue as descripted.
I also found the issue occured since commit 72469a63e610eb65233463294e5565c5f85fee02 version.
In other words, commit 0fbbee033906de763431e5e968288b979034f4f9 version is the last working version for me.

**Comment by zixaphir** [comment]
I apologize for this oversight. I'm not sure what chain of events causes version checking to fail, but latest update should fix it.



> Versions after Sep 23, 2023 cannot download preview image correctly.

I'll look into this, but in the future, please file separate issues for separate problems.
