### ISSUE TITLE
1.6.0 Startup error is reported

### ISSUE THREAD

**Issue by cjh1228** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#21]
*** Error loading script: civitai_helper.py
    Traceback (most recent call last):
      File "D:\StabilityMatrix\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StabilityMatrix\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StabilityMatrix\Data\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 31, in <module>
        "add_trigger_words_button": util.newer_version(util.webui_version(), '1.5.0', allow_equal=True),
      File "D:\StabilityMatrix\Data\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\util.py", line 253, in newer_version
        return parse_version(ver1) >= parse_version(ver2)
      File "D:\StabilityMatrix\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\packaging\version.py", line 52, in parse
        return Version(version)
      File "D:\StabilityMatrix\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\packaging\version.py", line 196, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object

**Comment by zixaphir** [comment]
I apologize for this oversight. I'm not sure what chain of events causes version checking to fail, but latest update should fix it.
