### ISSUE TITLE
Can't connect to Civitai after setting proxy | 在配置了代理后依然无法连接至civitai

### ISSUE THREAD

**Issue by WallBreakerNO4** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#30]
由于civitai在中国境内无法访问，我在我自己的局域网内设立了代理服务，提供http和socks5代理，并且在webui中设置了代理地址（如图所示）
Since civitai is not accessible within China, I set up a proxy service on my own LAN to provide http and socks5 proxies, and set up the proxy address in the webui (as shown in the picture)

![image](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/34301560/43a0c4ba-ec6b-46a2-950d-107b7433f4b2)
![image](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/34301560/a1e7e629-7e5c-48df-9e14-4a73de62d661)

但是我在civitai helper中进行任何需要访问civitai的操作都会报以下错误，同时我并没有在代理服务的后台发现任何代理请求
But any action I do in the civitai helper that requires access to civitai reports the following error, and I don't find any proxy requests in the backend of the proxy service
~~~
Traceback (most recent call last):
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/models/5285 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/wall/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/ch_lib/model_action_civitai.py", line 287, in check_models_new_version_to_md
    new_versions = civitai.check_models_new_version_by_model_types(model_types, 0.2)
  File "/home/wall/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/ch_lib/civitai.py", line 649, in check_models_new_version_by_model_types
    version = check_single_model_new_version(root, filename, model_type, delay)
  File "/home/wall/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/ch_lib/civitai.py", line 589, in check_single_model_new_version
    request = check_model_new_version_by_path(item, delay)
  File "/home/wall/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/ch_lib/civitai.py", line 537, in check_model_new_version_by_path
    model_info = get_model_info_by_id(model_id)
  File "/home/wall/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/ch_lib/civitai.py", line 146, in get_model_info_by_id
    content = civitai_get(f'{URLS["modelId"]}{model_id}')
  File "/home/wall/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/ch_lib/civitai.py", line 36, in civitai_get
    request = downloader.request_get(
  File "/home/wall/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/ch_lib/downloader.py", line 23, in request_get
    request = requests.get(
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/wall/stable-diffusion-webui/venv/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/models/5285 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
~~~

**Comment by WallBreakerNO4** [comment]
Here is my `Command Line Arguments` BTW
~~~
--listen --enable-insecure-extension-access --no-gradio-queue --api --theme dark --xformers
~~~
