### ISSUE TITLE
Something broke with the update a few versions ago

### ISSUE THREAD

**Issue by simonmcnair** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#36]
```
2023-10-29T12:08:40.257238787Z Civitai Helper: Checking preview image for model: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/ethernaldope_v10.safetensors
2023-10-29T12:08:40.257427129Z Civitai Helper: This image is NSFW: Mature
2023-10-29T12:08:40.561901785Z Civitai Helper: Start downloading from: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/8bf2a1cb-f27d-418c-ab1f-3a211d43717c/width=1024/2986612.jpeg
2023-10-29T12:08:40.561927235Z Civitai Helper: Target file path: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/ethernaldope_v10.preview.png
2023-10-29T12:08:40.561929064Z Civitai Helper: File size: 137730
2023-10-29T12:08:40.561930645Z Civitai Helper: Downloading to temp file: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/ethernaldope_v10.preview.png.downloading
2023-10-29T12:08:40.561932307Z Civitai Helper: Resuming partially downloaded file from progress: 137730
2023-10-29T12:08:40.652744677Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:40.652756519Z    416: Requested Range Not Satisfiable
2023-10-29T12:08:40.652758159Z Civitai Helper: Retrying
2023-10-29T12:08:40.734648572Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:40.734661495Z    416: Requested Range Not Satisfiable
2023-10-29T12:08:40.734663166Z Civitai Helper: Retrying
2023-10-29T12:08:40.810681140Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:40.810699554Z    416: Requested Range Not Satisfiable
2023-10-29T12:08:40.810701342Z Civitai Helper: Retrying
2023-10-29T12:08:40.882415724Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:40.882427651Z    416: Requested Range Not Satisfiable

2023-10-29T12:08:40.886573856Z Civitai Helper: Model metadata not needed for epicrealism_naturalSinRC1VAE.safetensors
2023-10-29T12:08:40.886575404Z Civitai Helper: Downloading model image.
2023-10-29T12:08:40.886576823Z Civitai Helper: Checking preview image for model: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/epicrealism_naturalSinRC1VAE.safetensors
2023-10-29T12:08:41.124596232Z Civitai Helper: Start downloading from: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/3822f91b-5f4e-4df6-8934-2a453f13b40e/width=960/2103034.jpeg
2023-10-29T12:08:41.124610054Z Civitai Helper: Target file path: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/epicrealism_naturalSinRC1VAE.preview.png
2023-10-29T12:08:41.124611851Z Civitai Helper: File size: 106983
2023-10-29T12:08:41.124613285Z Civitai Helper: Downloading to temp file: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/epicrealism_naturalSinRC1VAE.preview.png.downloading
2023-10-29T12:08:41.124614847Z Civitai Helper: Resuming partially downloaded file from progress: 106983
2023-10-29T12:08:41.203427659Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:41.203440316Z    416: Range Not Satisfiable
2023-10-29T12:08:41.203442073Z Civitai Helper: Retrying
2023-10-29T12:08:41.274891957Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:41.274915860Z    416: Range Not Satisfiable
2023-10-29T12:08:41.274917556Z Civitai Helper: Retrying
2023-10-29T12:08:41.353289468Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:41.353300786Z    416: Range Not Satisfiable
2023-10-29T12:08:41.353302620Z Civitai Helper: Retrying
2023-10-29T12:08:41.424637269Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:41.424649399Z    416: Range Not Satisfiable
2023-10-29T12:08:41.679650019Z Civitai Helper: Target file path: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/protogenInfinity_protogenInfinity.preview.png
2023-10-29T12:08:41.679651870Z Civitai Helper: File size: 98339
2023-10-29T12:08:41.679653531Z Civitai Helper: Downloading to temp file: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/protogenInfinity_protogenInfinity.preview.png.downloading
2023-10-29T12:08:41.679655132Z Civitai Helper: Resuming partially downloaded file from progress: 98339
2023-10-29T12:08:41.759944829Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:41.759959044Z    416: Range Not Satisfiable
2023-10-29T12:08:41.759960819Z Civitai Helper: Retrying
2023-10-29T12:08:41.826163552Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:41.826187581Z    416: Range Not Satisfiable
2023-10-29T12:08:41.826189267Z Civitai Helper: Retrying
2023-10-29T12:08:41.899455552Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:41.899467411Z    416: Range Not Satisfiable
2023-10-29T12:08:41.899469047Z Civitai Helper: Retrying
2023-10-29T12:08:41.966184171Z Civitai Helper: GET Request failed with error code:
2023-10-29T12:08:41.966196358Z    416: Range Not Satisfiable

2023-10-29T12:08:41.970193122Z Civitai Helper: Checking preview image for model: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/protogenX53Photorealism_protogenX53.safetensors
2023-10-29T12:08:42.225351148Z Civitai Helper: Start downloading from: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/6614bd63-e522-4826-27c5-5e93d335c000/width=3000/27601.jpeg
2023-10-29T12:08:42.225388738Z Civitai Helper: Target file path: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/protogenX53Photorealism_protogenX53.preview.png
2023-10-29T12:08:42.225494312Z Civitai Helper: File size: 1693215
2023-10-29T12:08:42.225501030Z Civitai Helper: Downloading to temp file: /stable-diffusion-webui/models/Stable-diffusion/Photorealistic/protogenX53Photorealism_protogenX53.preview.png.downloading
2023-10-29T12:08:42.225502908Z Civitai Helper: Resuming partially downloaded file from progress: 1431071
2023-10-29T12:08:42.622187819Z 
  0% 0.00/1.61M [00:00<?, ?iB/s]
 15% 256k/1.61M [00:00<00:00, 5.04MiB/s]

2023-10-29T12:08:42.629106272Z Civitai Helper: Creating model info for: test_1.safetensors
2023-10-29T12:08:42.629108374Z Civitai Helper: Use Memory Optimized SHA256
2023-10-29T12:08:47.626096164Z 2023-10-29 12:08:47 ERROR [asyncio] Exception in callback H11Protocol.timeout_keep_alive_handler()
2023-10-29T12:08:47.626110467Z handle: <TimerHandle when=680232.21970726 H11Protocol.timeout_keep_alive_handler()>
2023-10-29T12:08:47.626112604Z Traceback (most recent call last):
2023-10-29T12:08:47.626114150Z   File "/usr/local/lib/python3.10/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
2023-10-29T12:08:47.626115875Z     new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
2023-10-29T12:08:47.626117454Z KeyError: <class 'h11._events.ConnectionClosed'>
2023-10-29T12:08:47.626119038Z 
2023-10-29T12:08:47.626120434Z During handling of the above exception, another exception occurred:
2023-10-29T12:08:47.626121899Z 
2023-10-29T12:08:47.626123242Z Traceback (most recent call last):
2023-10-29T12:08:47.626124641Z   File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
2023-10-29T12:08:47.626126156Z     self._context.run(self._callback, *self._args)
2023-10-29T12:08:47.626127594Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 363, in timeout_keep_alive_handler
2023-10-29T12:08:47.626129214Z     self.conn.send(event)
2023-10-29T12:08:47.626130604Z   File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 468, in send
2023-10-29T12:08:47.626132108Z     data_list = self.send_with_data_passthrough(event)
2023-10-29T12:08:47.626133596Z   File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 493, in send_with_data_passthrough
2023-10-29T12:08:47.626135127Z     self._process_event(self.our_role, event)
2023-10-29T12:08:47.626136535Z   File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 242, in _process_event
2023-10-29T12:08:47.626138033Z     self._cstate.process_event(role, type(event), server_switch_event)
2023-10-29T12:08:47.626139491Z   File "/usr/local/lib/python3.10/site-packages/h11/_state.py", line 238, in process_event
2023-10-29T12:08:47.626141030Z     self._fire_event_triggered_transitions(role, event_type)
2023-10-29T12:08:47.626142487Z   File "/usr/local/lib/python3.10/site-packages/h11/_state.py", line 251, in _fire_event_triggered_transitions
2023-10-29T12:08:47.626144002Z     raise LocalProtocolError(
2023-10-29T12:08:47.626145446Z h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

2023-10-29T12:08:50.047813800Z Civitai Helper: Downloading to temp file: /stable-diffusion-webui/models/Lora/test_1.preview.png.downloading
2023-10-29T12:08:50.143231166Z 
  0% 0.00/114k [00:00<?, ?iB/s]*** API error: POST: http://localhost:7860/api/predict {'error': 'LocalProtocolError', 'detail': '', 'body': '', 'errors': "Can't send data when our state is ERROR"}
2023-10-29T12:08:50.143311256Z     Traceback (most recent call last):
2023-10-29T12:08:50.143317742Z       File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-10-29T12:08:50.143319672Z         await self.app(scope, receive, _send)
2023-10-29T12:08:50.143321176Z       File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 109, in __call__
2023-10-29T12:08:50.143322746Z         await response(scope, receive, send)
2023-10-29T12:08:50.143324193Z       File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2023-10-29T12:08:50.143325747Z         async with anyio.create_task_group() as task_group:
2023-10-29T12:08:50.143327310Z       File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2023-10-29T12:08:50.143328889Z         raise exceptions[0]
2023-10-29T12:08:50.143330356Z       File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2023-10-29T12:08:50.143331940Z         await func()
2023-10-29T12:08:50.143333378Z       File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 134, in stream_response
2023-10-29T12:08:50.143334936Z         return await super().stream_response(send)
2023-10-29T12:08:50.143336374Z       File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 255, in stream_response
2023-10-29T12:08:50.143337913Z         await send(
2023-10-29T12:08:50.143339385Z       File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in _send
2023-10-29T12:08:50.143345034Z         await send(message)
2023-10-29T12:08:50.143346459Z       File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 490, in send
2023-10-29T12:08:50.143348001Z         output = self.conn.send(event=response)
2023-10-29T12:08:50.143349535Z       File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 468, in send
2023-10-29T12:08:50.143351068Z         data_list = self.send_with_data_passthrough(event)
2023-10-29T12:08:50.143352510Z       File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 483, in send_with_data_passthrough
2023-10-29T12:08:50.143354098Z         raise LocalProtocolError("Can't send data when our state is ERROR")
2023-10-29T12:08:50.143355692Z     h11._util.LocalProtocolError: Can't send data when our state is ERROR
2023-10-29T12:08:50.143357185Z 
2023-10-29T12:08:50.143358551Z ---
2023-10-29T12:08:50.144046054Z ERROR:    Exception in ASGI application
2023-10-29T12:08:50.144049749Z Traceback (most recent call last):
2023-10-29T12:08:50.144051321Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2023-10-29T12:08:50.144052974Z     result = await app(  # type: ignore[func-returns-value]
2023-10-29T12:08:50.144054481Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-10-29T12:08:50.144056037Z     return await self.app(scope, receive, send)
2023-10-29T12:08:50.144057482Z   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 273, in __call__
2023-10-29T12:08:50.144058992Z     await super().__call__(scope, receive, send)
2023-10-29T12:08:50.144060428Z   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-10-29T12:08:50.144061934Z     await self.middleware_stack(scope, receive, send)
2023-10-29T12:08:50.144063381Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-10-29T12:08:50.144064916Z     raise exc
2023-10-29T12:08:50.144066354Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-10-29T12:08:50.144067885Z     await self.app(scope, receive, _send)
2023-10-29T12:08:50.144069304Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 109, in __call__
2023-10-29T12:08:50.144070796Z     await response(scope, receive, send)
2023-10-29T12:08:50.144072222Z   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2023-10-29T12:08:50.144073738Z     async with anyio.create_task_group() as task_group:
2023-10-29T12:08:50.144075194Z   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2023-10-29T12:08:50.144080655Z     raise exceptions[0]
2023-10-29T12:08:50.144082148Z   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2023-10-29T12:08:50.144083668Z     await func()
2023-10-29T12:08:50.144085050Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 134, in stream_response
2023-10-29T12:08:50.144086614Z     return await super().stream_response(send)
2023-10-29T12:08:50.144088077Z   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 255, in stream_response
2023-10-29T12:08:50.144089624Z     await send(
2023-10-29T12:08:50.144091013Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in _send
2023-10-29T12:08:50.144092528Z     await send(message)
2023-10-29T12:08:50.144093957Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 490, in send
2023-10-29T12:08:50.144095666Z     output = self.conn.send(event=response)
2023-10-29T12:08:50.144097109Z   File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 468, in send
2023-10-29T12:08:50.144098611Z     data_list = self.send_with_data_passthrough(event)
2023-10-29T12:08:50.144100036Z   File "/usr/local/lib/python3.10/site-packages/h11/_connection.py", line 483, in send_with_data_passthrough
2023-10-29T12:08:50.144101549Z     raise LocalProtocolError("Can't send data when our state is ERROR")
2023-10-29T12:08:50.144103060Z h11._util.LocalProtocolError: Can't send data when our state is ERROR
2023-10-29T12:08:50.144315108Z 'AsyncRequest' object has no attribute '_json_response_data'
2023-10-29T12:09:06.578046698Z 9519d49c28ef256fc354dbd46a75bc048d8201ec8069b8003dabff23573f8173
```

**Comment by simonmcnair** [comment]
possibly fixable with https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/pull/34 ?

**Comment by zixaphir** [comment]
I honestly have no idea what could cause that type of error

**Comment by QuietNoise** [comment]
I can confirm this is happening intermittently and possibly is related to connection issues with civitai.com. 
Today it happened to me to almost all new SDXL checkpoints but never to SD 1.5 ones, so I thought it is file size related or something but then SDXL loras also got them errors.
Then the errors got away all of sudden. I downloaded bunch of new models and deleted several png, info and json files to test just that but the errors didn't show up since.

**Comment by zixaphir** [comment]
I'm going to be tracking this issue here: https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/issues/39

I'm still not sure what the cause of it is but my current theory is that it might be related to a poor connection to Civitai.
