### ISSUE TITLE
Scanning hangs on model and doesnt complete since latest update

### ISSUE THREAD

**Issue by randykoala** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#48]
Scanning models hangs on first model with error in log file as below

Civitai Helper: Existing model image found. Skipping.
Civitai Helper: Creating model info for: limitlessvisionxl_v1.safetensors
Civitai Helper: Using SD Webui SHA256
ERROR:asyncio:Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=83465.812 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "C:\Users\myuser\SD Nov 2023\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\myuser\SD Nov 2023\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 363, in timeout_keep_alive_handler
    self.conn.send(event)
  File "C:\Users\myuser\SD Nov 2023\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\Users\myuser\SD Nov 2023\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 493, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "C:\Users\myuser\SD Nov 2023\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 242, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "C:\Users\myuser\SD Nov 2023\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "C:\Users\myuser\SD Nov 2023\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 251, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

**Comment by zixaphir** [comment]
This issue is current being tracked in https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/issues/39
