### ISSUE TITLE
TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by tranzmatt** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#65]
## Have you read document?

Yes

## Have you checked console log window's msg?

Yes

## Describe Issue

Type Error when trying to Download Model->Get Model Info by Cititai Url

https://civitai.com/models/243494/majicmerge?modelVersionId=274741

## Console log's msg or screenshot for function issue

```Traceback (most recent call last):
  File "/home/automatic-stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/automatic-stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/automatic-stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/automatic-stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/automatic-stable-diffusion-webui/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/automatic-stable-diffusion-webui/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/automatic-stable-diffusion-webui/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/automatic-stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/automatic-stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/sections.py", line 266, in update_dl_inputs
    filename = state["filenames"][dl_version]
               ~~~~~^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'```

**Comment by zixaphir** [comment]
I'm not 100% sure what caused this but is it still occurring?
