### ISSUE TITLE
Unable to install lycoris in the lycoris folder

### ISSUE THREAD

**Issue by CasanovaSan** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#81]
So when i am tryin to install a lycoris it gives me this error

```Civitai Helper: Searching local model by version id
Civitai Helper: folder: D:\stable-diffusion-webui-forge\models\LyCORIS\
Civitai Helper: version_id: 337459
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/337459
Civitai Helper: Target file path: D:\stable-diffusion-webui-forge\models\LyCORIS\moniam-v1-lokr.safetensors
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\stable-diffusion-webui-forge\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 796, in dl_model_by_input
    for result in download_files(filename, folder, ver_info, headers, filetypes, dl_all, duplicate):
  File "D:\stable-diffusion-webui-forge\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 635, in download_files
    for result in downloader.dl_file(
  File "D:\stable-diffusion-webui-forge\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\downloader.py", line 336, in dl_file
    total_size = int(response.headers['Content-Length'])
  File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'```

and then when i try to install a lora, it won't work, but if i install a lora it works, (the extension only breaks when i try to installa lycoris in the lycoris folder)

**Comment by CasanovaSan** [comment]
Closing this, my dummass forgot to get the api key, now it owrks
