### ISSUE TITLE
Error 416: range not satisfiable

### ISSUE THREAD

**Issue by Kaneda56** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#87]
I have the error "416: Range Not Satisfiable" when I'm scanning
```
Civitai Helper: Checking preview image for model: S:\sept23\stable-diffusion-webui\models\Stable-diffusion\Réaliste\analogMadness_v70.safetensors
Civitai Helper: This image is NSFW: Soft
Civitai Helper: Start downloading from: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/753f6342-592f-47a0-bfd0-8a98dca32ddc/width=1152/4559649.jpeg
Civitai Helper: Target file path: S:\sept23\stable-diffusion-webui\models\Stable-diffusion\Réaliste\analogMadness_v70.preview.png
Civitai Helper: File size: 138874 (135.62K)
Civitai Helper: Downloading to temp file: S:\sept23\stable-diffusion-webui\models\Stable-diffusion\Réaliste\analogMadness_v70.preview.png.downloading
Civitai Helper: Resuming partially downloaded file from progress: 138874
Civitai Helper: GET Request failed with error code:
   416: Range Not Satisfiable
Traceback (most recent call last):
  File "S:\sept23\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\sept23\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "S:\sept23\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "S:\sept23\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "S:\sept23\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "S:\sept23\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "S:\sept23\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
```

Issue is the same with Forge and Automatic 1111

Thanks for help

**Comment by zixaphir** [comment]
Made some changes: https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/commit/d1e20e84aec261a059f5558d35d4066c42178df6

Can you update and try again?

**Comment by Kaneda56** [comment]
Yes it's works now. Thanks !
