### ISSUE TITLE
Specific model returning 404 Not Found (but model exists)

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#98]
## Have you read document?
I have read many documents. Anything in particular you were wondering about?

## Have you checked console log window's msg?
Yes.

## Describe Issue
This model: https://civitai.com/models/386952
Seems to break CivitAIHelper for me.

I get a 404: Not found, and the process stops for the rest of the scan.

If I remove the model, the scan finishes successfully, but if I put it back, it fails again in the same way.
It doesn't matter where I put the model.

## Console log's msg or screenshot for function issue
Civitai Helper: Existing model image found. Skipping.
Civitai Helper: Creating model info for: GreenArmyMen1024.safetensors
Civitai Helper: model action sha256: dcf8f8c2d0c4f523807097b11f8cca919d0285aaa27a0d07528aeb07bec6df0e
Civitai Helper: Request model info from civitai
Civitai Helper: Fetching Parent Model Information
Civitai Helper: Request model info from civitai: 386952
Civitai Helper: GET Request failed with error code:
   404: Not Found
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\AI\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui-forge\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 162, in scan_model
    for result in scan_single_model(filepath, model_type, refetch_old, delay):
  File "C:\AI\stable-diffusion-webui-forge\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 90, in scan_single_model
    model_info = civitai.get_model_info_by_hash(sha256_hash)
  File "C:\AI\stable-diffusion-webui-forge\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 117, in get_model_info_by_hash
    content = append_parent_model_metadata(content)
  File "C:\AI\stable-diffusion-webui-forge\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 86, in append_parent_model_metadata
    content["creator"] = parent_model.get("creator", "{}")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by zixaphir** [comment]
Your Civitai helper extension is old. The current extension logs the version number any time it logs to the console. 

As for the model 404'ing, that appears to be an issue on Civitai's end. When I query the API for model id `386952`, it shows there's no model with that id.

**Comment by MNeMoNiCuZ** [comment]
Updating did indeed fix it! Thanks!
